"""empty message

Revision ID: 162d2e7a214a
Revises: 2d517273af58
Create Date: 2022-10-15 00:14:27.784103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '162d2e7a214a'
down_revision = '2d517273af58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_google_account', sa.Boolean(), nullable=True))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_column('users', 'is_google_account')
    # ### end Alembic commands ###
